package com.test.genericservicewisetable.enums;

public enum PaymentStatus {
    INITIALIZED,

    PROCESSING_PAYMENT,
    PROCESSING_REFUND,

    SUCCEEDED_PAYMENT,
    SUCCEEDED_REFUND,

    FAILED_PAYMENT,
    FAILED_REFUND,

    RE_SUCCEEDED_PAYMENT,
    RE_SUCCEEDED_REFUND,

    RE_FAILED_PAYMENT,
    RE_FAILED_REFUND,

    RE_NOT_FOUND_PAYMENT,
    RE_NOT_FOUND_REFUND,

    INITIALIZED_CHECK_BILL,
    PROCESSING_CHECK_BILL,
    FAILED_CHECK_BILL,
    PROCESSING_FORCE_CHECK_BILL,

    INITIALIZED_PAY_BILL,
    PROCESSING_PAY_BILL,
    SUCCEEDED_PAY_BILL,
    RE_SUCCEEDED_PAY_BILL,
    FAILED_PAY_BILL,
    RE_FAILED_PAY_BILL,
    RE_NOT_FOUND_PAY_BILL
}
